"""
Django settings for imagi project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from the backend/django/ directory
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fail closed: default to False so a misconfigured/unset env never exposes
# debug pages or stack traces in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# Which tier this process serves in the split deployment. Both tiers run this
# same image against the same Postgres and SECRET_KEY; only nginx routing and
# this flag differ. See the Dockerfile CMD and the frontend nginx.conf.
#  - 'web': stateless API — auth, payments, project metadata. Reads the
#    ProjectFile DB mirror; must never write a working copy to disk (its disk
#    is ephemeral, so a stray write silently diverges from the source of
#    truth). project_files_service.ensure_workspace_tier() enforces this.
#  - 'workspace': the stateful tier that owns the on-disk working copies under
#    PROJECTS_ROOT (on a persistent volume) and runs the dev servers, headless
#    browser preview, and agent runs. All disk-touching endpoints route here.
#  - '' (unset): single-process deployments — local dev, tests, a non-split
#    box — where one process owns everything. The tier guard is inert here.
IMAGI_ROLE = os.environ.get('IMAGI_ROLE', '').strip().lower()

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback: a publicly-known key would allow session-cookie /
# signed-token forgery. Require it in production; allow an ephemeral
# dev-only key strictly when DEBUG is on so local commands still work.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY environment variable must be set when DEBUG is False.'
        )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

# Railway injects these at runtime — include them so the healthcheck's
# Host header is accepted without needing to manually set DJANGO_ALLOWED_HOSTS.
for _railway_host_var in ('RAILWAY_PUBLIC_DOMAIN', 'RAILWAY_PRIVATE_DOMAIN'):
    _railway_host = os.environ.get(_railway_host_var)
    if _railway_host and _railway_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_railway_host)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Local apps
    'apps.Home',
    'apps.Auth',
    'apps.Payments',
    'apps.Imagi.ProjectManager',
    'apps.Imagi.Marketing',
    'apps.Imagi.Sell',
    'apps.Imagi.Operate',
    'apps.Imagi.Build',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imagi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imagi.wsgi.application'
# Served over ASGI in production: the agent streams its run over SSE, which
# needs async request handling to avoid tying up a worker per run.
ASGI_APPLICATION = 'imagi.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# In production (Railway) we read DATABASE_URL, which should be set to the
# reference variable ${{ Postgres.DATABASE_URL }} on the backend service.
# Locally, DATABASE_URL is unset and we fall back to SQLite.

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    _db = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db.path.lstrip('/'),
            'USER': _db.username or '',
            'PASSWORD': _db.password or '',
            'HOST': _db.hostname or '',
            'PORT': str(_db.port) if _db.port else '',
            'CONN_MAX_AGE': 600,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # The initial build runs one agent per page concurrently, so several
            # threads now write here at once — which SQLite's default rollback
            # journal handles badly: a single writer blocks readers too, and a
            # blocked writer gives up with "database is locked". WAL lets
            # readers run through a write, and the longer timeout makes a
            # contended writer wait its turn instead of failing the page it was
            # building. Development only; production is Postgres above.
            'OPTIONS': {
                'init_command': 'PRAGMA journal_mode=WAL;',
                'timeout': 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    # Log unexpected errors and return a safe generic 500 (never leak str(exc)).
    'EXCEPTION_HANDLER': 'imagi.exception_handler.api_exception_handler',
    # Rates for the throttles applied per view (apps.Auth.api.throttles,
    # apps.Imagi.Sell.api.throttles). No DEFAULT_THROTTLE_CLASSES: only the
    # endpoints an anonymous caller can abuse are limited, so authenticated
    # product traffic is untouched.
    'DEFAULT_THROTTLE_RATES': {
        'auth_signin': '10/min',
        'auth_register': '20/hour',
        'storefront_checkout': '30/hour',
    },
}


# CORS / CSRF for Vue SPA frontend
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = os.environ.get(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

# Cookie config so the Vue SPA can read csrftoken and send sessionid
CSRF_COOKIE_HTTPONLY = False  # frontend reads it from document.cookie
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# TLS terminates at the edge and nginx forwards X-Forwarded-Proto, so Django
# needs to be told about it — without this request.is_secure() is always False
# behind the proxy and the flags below would never apply. Off in DEBUG, where
# the dev servers are plain HTTP.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# SECURE_SSL_REDIRECT is deliberately left off: the edge already serves HTTPS
# only, while the Railway healthcheck and the backend<->workspace calls travel
# plain HTTP over *.railway.internal, and a redirect would break both.


# Stripe / Payments
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
# Empty means "not configured", never "verify with an empty key": the webhook
# view and StripeService.verify_webhook_event both refuse to run without it,
# and apps.Payments.apps.stripe_webhook_secret_check reports it at deploy time.
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')


# Products / Imagi builder
#
# Hardcoded platform defaults applied to every user's project. Imagi is built
# for nontechnical users, so none of this is exposed in the product today —
# every project starts from the same defaults. If we later add a settings
# surface where users can adjust some of these, it should read/override this
# block rather than replace it. Code reads the block via
# getattr(settings, 'IMAGI_BUILDER', {}) with matching fallbacks, so tests
# and scripts work without it.
IMAGI_BUILDER = {
    # Public suite model id the agent runs on (see Build/services/models_service.py
    # for the mapping to real OpenAI model ids).
    'DEFAULT_MODEL': 'gpt-5.6-terra',
    # Reasoning effort used when a request doesn't specify one.
    'DEFAULT_REASONING_EFFORT': 'medium',
    # Upper bound on agent-loop iterations for a single request.
    'MAX_AGENT_TURNS': 30,
    # Initial build (the first build of a new project, dispatched from the
    # project's main thread to a background subagent) runs headless and
    # unattended, so it gets its own model and tighter caps.
    #
    # TIME is the primary bound, because the founder is sitting there waiting:
    # the whole build — first run plus any repair runs — is held to this many
    # seconds, and whatever is finished and sound by then is what ships. The
    # project already holds a working home + auth scaffold from the moment it is
    # created, so a build that stops early degrades to "less tailoring", never
    # to a broken or empty app.
    # The target is a 30-second wait, so the agents' own runs get 28: the
    # founder additionally waits on the work either side of them (worktree
    # setup, then the merges and database mirror on the way out) — measured at
    # ~2s combined.
    #
    # The budget is shared by every page, not spent per page: the pages below
    # are built CONCURRENTLY, one subagent each, so half a minute buys all of
    # them rather than just one. Wall clock is the slowest page; what scales
    # with the list is spend, roughly linearly (three pages ≈ three times the
    # tokens), which is why COST_BUDGET_USD below is per page.
    'INITIAL_BUILD_MODEL': 'gpt-5.6-terra',
    'INITIAL_BUILD_TIME_BUDGET_S': 28,
    # Pages the first build writes, one subagent per entry, each owning a
    # single already-routed view file (see initial_build_service.PAGE_BRIEFS
    # for the briefs and prebuilt_apps/home.py for the scaffold they rewrite).
    # Empty or unset builds all of them; trimming the list is the direct lever
    # on what a project creation costs.
    'INITIAL_BUILD_PAGES': ['home', 'about', 'contact'],
    # First builds create UI from a description rather than reasoning about
    # existing code, so they run at low effort: it roughly halves per-turn
    # latency, which buys more pages inside the time budget than deeper
    # reasoning does.
    'INITIAL_BUILD_REASONING_EFFORT': 'low',
    # Cost and turns are runaway backstops now, not the operative limit — the
    # time budget stops a normal build long before either binds. Both are PER
    # PAGE, so the ceiling for a whole build is this times the page count.
    # NOTE: the cost figure is priced with the *suite retail* rates in
    # models_service (what a run is displayed as costing), which are a multiple
    # of the underlying API price — so this is deliberately well above real
    # expected spend. Sized so it never cuts a build short on its own; time
    # does that.
    'INITIAL_BUILD_COST_BUDGET_USD': 1.50,
    'INITIAL_BUILD_MAX_TURNS': 12,
    # A build that stops at a cap can leave a page importing a component it
    # never wrote, which takes the whole preview down. Such a build is not
    # merged; instead the subagent gets a short follow-up run to repair the
    # dangling references — but only from whatever time is left in the budget
    # above, so repair can never extend the founder's wait. At half a minute
    # there is rarely room for even one, which is why the first-build prompt
    # asks for a single self-contained file: a build that writes no cross-file
    # references cannot leave a dangling one to repair.
    'INITIAL_BUILD_REPAIR_ATTEMPTS': 1,
    'INITIAL_BUILD_REPAIR_COST_BUDGET_USD': 0.50,
    'INITIAL_BUILD_REPAIR_MAX_TURNS': 6,
    # Skip a repair run that cannot plausibly finish in the time left, rather
    # than starting one that will be killed mid-edit (which tends to leave more
    # dangling references than it fixes).
    'INITIAL_BUILD_MIN_REPAIR_SECONDS': 8,
    # Attach OpenAI's hosted web-search tool to the agent.
    'ENABLE_WEB_SEARCH': True,
    # Apps scaffolded into every new project. Payment pages are deliberately
    # not scaffolded — the Sell workspace installs prebuilt, Stripe-hosted
    # checkout pages on demand (apps.Imagi.Sell.services.payment_templates).
    'DEFAULT_APPS': ['home', 'auth'],
}

# Root directory where ProjectManager writes generated user projects. This
# working copy on disk is the source of truth — projects run from it in both
# development and production. The database (Build.ProjectFile rows) keeps a
# mirror of these files for debugging (browsable from the Build module) and
# as a backup from which a missing working copy can be rehydrated.
# Kept outside the repository in every environment so git operations (clean,
# fresh clones, worktrees) never touch it.
#  - This used to live under BASE_DIR in development, so generated projects were
#    easy to browse while testing the agent. That cost more than it was worth:
#    every git worktree got its own copy, so the same project was duplicated
#    across checkouts (hundreds of MB), and because Project rows stored an
#    absolute path, a project created in one worktree resolved into that
#    worktree forever — deleting it stranded the files. Paths are now stored
#    relative to this root (see Project.project_dir), so one shared directory
#    serves every checkout. Browse it directly at ~/.imagi/projects.
#  - Same reasoning that already moved FRONTEND_DEP_STORE_ROOT out of the
#    checkout below.
_DEFAULT_PROJECTS_ROOT = os.path.expanduser('~/.imagi/projects')
PROJECTS_ROOT = os.path.expanduser(
    os.environ.get('PROJECTS_ROOT', _DEFAULT_PROJECTS_ROOT)
)

# Shared, content-addressed store of installed frontend dependencies. Every
# generated project ships the same package.json, so instead of installing a
# private node_modules per project (slow, and re-run on every production
# rebuild since PROJECTS_ROOT is ephemeral), each dependency set is installed
# here once and projects symlink their node_modules at it.
#  - Deliberately kept out of PROJECTS_ROOT so it can live on a path that
#    persists across deploys. In production the Docker image prewarms it at
#    build time (see the warm_frontend_deps management command), baking the
#    install into the image so it survives every redeploy.
#  - In development it also lives outside the repository. Unlike the generated
#    projects (small, text, worth browsing), a slot is hundreds of megabytes of
#    node_modules with nothing to inspect, and keeping it under BASE_DIR
#    duplicated that per git worktree and left it sitting in the checkout.
_DEFAULT_FRONTEND_DEP_STORE_ROOT = (
    os.path.expanduser('~/.imagi/frontend-deps')
    if DEBUG
    else '/opt/imagi/frontend-deps'
)
FRONTEND_DEP_STORE_ROOT = os.path.expanduser(
    os.environ.get('FRONTEND_DEP_STORE_ROOT', _DEFAULT_FRONTEND_DEP_STORE_ROOT)
)

# Build workspace browser preview. A headless Chromium runs on this host next
# to each previewed project's dev servers; the workspace streams frames and
# forwards input through the API, so the setup is identical in development
# and production (the Docker image installs Chromium and sets the path).
# When empty, common Chrome/Chromium install locations are searched.
BROWSER_PREVIEW_EXECUTABLE = os.environ.get('BROWSER_PREVIEW_EXECUTABLE', '')

# Preview sessions (browser + dev servers) idle longer than this many seconds
# are shut down opportunistically when another preview starts. 0 disables.
BROWSER_PREVIEW_IDLE_TIMEOUT = int(os.environ.get('BROWSER_PREVIEW_IDLE_TIMEOUT', '1800'))


# Marketing / Twilio
# Public base URL Twilio uses for webhooks (delivery status callbacks and
# inbound messages), e.g. https://api.example.com — no trailing slash needed.
# Falls back to the Railway public domain when deployed there. When empty,
# campaigns still send, but delivery statuses only update via the manual
# "sync" action and inbound messages can't be received.
MARKETING_WEBHOOK_BASE_URL = os.environ.get('MARKETING_WEBHOOK_BASE_URL', '')
if not MARKETING_WEBHOOK_BASE_URL and os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    MARKETING_WEBHOOK_BASE_URL = f"https://{os.environ['RAILWAY_PUBLIC_DOMAIN']}"

# Safety cap on recipients per campaign send (synchronous dispatch loop).
MARKETING_MAX_CAMPAIGN_RECIPIENTS = int(
    os.environ.get('MARKETING_MAX_CAMPAIGN_RECIPIENTS', '500')
)


# Sell / Stripe (per-project storefront checkout)
# Public base URL Stripe uses for the per-project webhook endpoint, shown in
# Sell settings so users can register it in their Stripe dashboard. Falls
# back to the Marketing base (same host serves both). When empty, orders
# still record — payment status updates via the manual "sync" action or the
# success-page poll instead of webhooks.
SELL_WEBHOOK_BASE_URL = os.environ.get('SELL_WEBHOOK_BASE_URL', MARKETING_WEBHOOK_BASE_URL)

# Public base URL of this backend that the prebuilt payment pages (dropped
# into generated user projects by the Sell workspace) call for their
# storefront API. Baked into the generated code at install time. Falls back
# to the webhook base, then to the local dev server.
SELL_STOREFRONT_API_BASE = os.environ.get(
    'SELL_STOREFRONT_API_BASE',
    SELL_WEBHOOK_BASE_URL or 'http://localhost:8000',
)
