# Generated by Django 5.1.6 on 2025-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='project',
        ),
        migrations.AddField(
            model_name='conversation',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
