export { default as WorkspaceEditor } from './WorkspaceEditor.vue'
export { default as WorkspaceToolbar } from './WorkspaceToolbar.vue'
export { default as WorkspacePreview } from './WorkspacePreview.vue'
export { default as WorkspaceChat } from './WorkspaceChat.vue'
export { default as WorkspaceBackground } from './WorkspaceBackground.vue'
export { default as WorkspaceError } from './WorkspaceError.vue'
export { default as WorkspaceAppsSimple } from './WorkspaceAppsSimple.vue'
export { default as WorkspaceAppsAdvanced } from './WorkspaceAppsAdvanced.vue'
