export { default as WorkspaceChat } from './WorkspaceChat.vue'
export { default as WorkspaceBackground } from './WorkspaceBackground.vue'
export { default as WorkspaceError } from './WorkspaceError.vue'
export { default as AppsList } from './AppsList.vue'
export { default as AppDetailView } from './AppDetailView.vue'
