version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY:-}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount logs for development debugging
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  # Development service for local development
  frontend-dev:
    build:
      context: .
      target: build-stage
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY:-}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev
    networks:
      - app-network

volumes:
  nginx_logs:

networks:
  app-network:
    driver: bridge 