# Generated by Django 5.1.6 on 2025-02-11 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_fix_duplicate_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of project generation', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, help_text='Last time project files were generated', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Optional project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft deletion status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_path',
            field=models.CharField(help_text='Absolute path to project directory', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_active'], name='ProjectMana_user_id_cb9acd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='ProjectMana_slug_5452bb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['generation_status'], name='ProjectMana_generat_57e4d2_idx'),
        ),
    ]
