# Generated by Django 5.1.3 on 2024-12-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Builder', '0003_project_conversation_project'),
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.userproject'),
        ),
    ]
