# Generated by Django 5.1.6 on 2025-03-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='anthropic', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconversation',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet')], max_length=50),
        ),
    ]
