# Generated by Django 5.1.6 on 2025-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_use_centralized_model_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
