# Generated by Django 6.0.7 on 2026-07-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ProjectManager", "0002_rename_oasis_to_imagi_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added manually"),
                            ("checkout", "Stripe checkout"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_customers",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("fulfilled", "Fulfilled"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount_total_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="Sell.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_orders",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        help_text="Price in the smallest currency unit, e.g. cents"
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active products can be bought"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_products",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("unit_price_cents", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Sell.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="Sell.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_publishable_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_secret_key_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "stripe_webhook_secret_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD — US Dollar"),
                            ("eur", "EUR — Euro"),
                            ("gbp", "GBP — British Pound"),
                            ("cad", "CAD — Canadian Dollar"),
                            ("aud", "AUD — Australian Dollar"),
                        ],
                        default="usd",
                        help_text="Currency for all products and checkout sessions",
                        max_length=3,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_settings",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sell Settings",
                "verbose_name_plural": "Sell Settings",
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("project", "email"),
                name="unique_sell_customer_email_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["project", "status"], name="Sell_order_project_38610f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["project", "-created_at"], name="Sell_order_project_2561f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["project", "is_active"], name="Sell_produc_project_cfe1b4_idx"
            ),
        ),
    ]
