# Generated by Django 6.0.4 on 2026-10-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManager", "0006_project_app_details"),
        ("Sell", "0002_product_billing_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_account_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Stripe account the meter and price above live on",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_meter_event_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_meter_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_price_signature",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="usage_unit_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="usage_unit_label",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="app_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="connect_account_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="connect_charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="connect_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="connect_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="payment_models",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sellsettings",
            name="server_key_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="billing_interval",
            field=models.CharField(
                choices=[
                    ("one_time", "One-time purchase"),
                    ("month", "Monthly subscription"),
                    ("year", "Yearly subscription"),
                    ("usage", "Pay as you go"),
                ],
                default="one_time",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("stripe_subscription_id", models.CharField(max_length=255)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status", models.CharField(default="incomplete", max_length=30)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="Sell.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="Sell.product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_subscriptions",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("quantity", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="Sell.product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_usage_events",
                        to="ProjectManager.project",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="Sell.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["project", "status"], name="Sell_subscr_project_de564b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["project", "customer_email"],
                name="Sell_subscr_project_8486be_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("project", "stripe_subscription_id"),
                name="unique_sell_subscription_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["project", "-created_at"], name="Sell_usagee_project_eeb689_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageevent",
            constraint=models.UniqueConstraint(
                fields=("project", "idempotency_key"),
                name="unique_sell_usage_event_key_per_project",
            ),
        ),
    ]
