# Generated by Django 6.0.4 on 2026-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_move_imagi_projects_into_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_preferences',
            field=models.TextField(blank=True, default='', help_text='Optional founder-provided design/style direction for the initial AI build'),
        ),
    ]
