# Generated by Django 6.0.4 on 2026-10-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManager", "0005_project_dir_relative_to_projects_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional founder-provided account of how the app should work (what people can do, what it keeps track of, what it must be like); the initial AI build turns it into a light system design",
            ),
        ),
    ]
