# Generated by Django 6.0.4 on 2026-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManager", "0006_project_app_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the owner opened the project's workspace preview. The most recent few get their preview warmed up at sign-in.",
                null=True,
            ),
        ),
    ]
