# Generated by Django 6.0.4 on 2026-10-08 20:29

import apps.Imagi.Operate.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Operate", "0001_initial"),
        ("ProjectManager", "0006_project_app_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("live_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "site_key",
                    models.CharField(
                        default=apps.Imagi.Operate.models.new_site_key,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operate_monitor",
                        to="ProjectManager.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=300)),
                ("visitor", models.CharField(max_length=32)),
                (
                    "referrer_host",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operate_page_views",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="Operate_pag_project_0817a8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UptimeCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_up", models.BooleanField()),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operate_uptime_checks",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "checked_at"],
                        name="Operate_upt_project_08b525_idx",
                    )
                ],
            },
        ),
    ]
