# Generated by Django 5.1.6 on 2025-03-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional project description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft deletion status')),
                ('project_path', models.CharField(help_text='Absolute path to project directory', max_length=500)),
                ('last_generated_at', models.DateTimeField(blank=True, help_text='Last time project files were generated', null=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of project generation', max_length=20)),
                ('is_initialized', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='ProjectMana_user_id_cb9acd_idx'), models.Index(fields=['slug'], name='ProjectMana_slug_5452bb_idx'), models.Index(fields=['generation_status'], name='ProjectMana_generat_57e4d2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_project_name_per_user')],
            },
        ),
    ]
