# Generated by Django 5.1.6 on 2025-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_alter_project_options_project_generation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
