# Generated by Django 6.0.4 on 2026-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_subscription_usageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
