# Generated by Django 5.1.4 on 2025-02-01 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_creditpackage_payment_credits_payment_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost_per_use', models.DecimalField(decimal_places=4, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_ai_model',
            },
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.creditpackage'),
        ),
        migrations.CreateModel(
            name='AIModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('success', models.BooleanField(default=True)),
                ('context', models.JSONField(default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Payments.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_ai_model_usage',
            },
        ),
    ]
