# Generated by Django 5.2.16 on 2026-07-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketing", "0001_initial"),
        ("ProjectManager", "0003_move_imagi_projects_into_build"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google Ads"), ("meta", "Meta Ads")],
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("account_id", models.CharField(blank=True, default="", max_length=32)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "objective",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta objective or Google advertising channel type",
                        max_length=100,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conversions",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_campaigns",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-spend", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="Marketing_a_project_ec575d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "provider", "external_id"),
                        name="unique_ad_campaign_per_project_provider",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google Ads"), ("meta", "Meta Ads")],
                        max_length=10,
                    ),
                ),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta ad account ID or Google Ads customer ID, digits only",
                        max_length=32,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_connections",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "provider"),
                        name="unique_ad_connection_provider_per_project",
                    )
                ],
            },
        ),
    ]
