# Generated by Django 6.0.4 on 2026-10-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketing", "0002_adcampaign_adconnection"),
        ("ProjectManager", "0006_project_app_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google Ads"), ("meta", "Meta Ads")],
                        default="google",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("website", "Website visits"),
                            ("calls", "Phone calls"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("final_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("headlines", models.JSONField(blank=True, default=list)),
                ("descriptions", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_drafts",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
