# Generated by Django 6.0.7 on 2026-07-10 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ProjectManager", "0002_rename_oasis_to_imagi_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "Text message"), ("voice", "Voice call")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message text (SMS) or spoken script (voice). Supports {{first_name}}, {{last_name}} and {{name}} placeholders."
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all", "All subscribed contacts"),
                            ("tags", "Contacts with any of the selected tags"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("audience_tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_campaigns",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format, e.g. +15551234567",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tag strings used for audience segmentation",
                    ),
                ),
                (
                    "consent",
                    models.CharField(
                        choices=[
                            ("subscribed", "Subscribed"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="subscribed",
                        help_text="Only subscribed contacts receive campaigns",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added manually"),
                            ("import", "Imported"),
                            ("inbound", "Inbound message"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_contacts",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twilio_account_sid",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "twilio_auth_token_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "twilio_phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio phone number used as the sender, in E.164 format",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format, e.g. +15551234567",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "twilio_messaging_service_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional Messaging Service SID; required for scheduled campaigns",
                        max_length=64,
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        choices=[
                            ("Polly.Joanna", "Joanna (female, US English)"),
                            ("Polly.Matthew", "Matthew (male, US English)"),
                            ("Polly.Amy", "Amy (female, British English)"),
                            ("Polly.Brian", "Brian (male, British English)"),
                            ("alice", "Alice (classic)"),
                        ],
                        default="Polly.Joanna",
                        help_text="Text-to-speech voice used for voice broadcasts",
                        max_length=50,
                    ),
                ),
                (
                    "account_friendly_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_settings",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Settings",
                "verbose_name_plural": "Marketing Settings",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "Text message"), ("voice", "Voice call")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                (
                    "from_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_number", models.CharField(blank=True, default="", max_length=20)),
                (
                    "twilio_sid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("status", models.CharField(default="queued", max_length=32)),
                ("error_code", models.CharField(blank=True, default="", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="Marketing.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="Marketing.contact",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_messages",
                        to="ProjectManager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["project", "status"], name="Marketing_c_project_efd700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["project", "consent"], name="Marketing_c_project_961e81_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("project", "phone_number"),
                name="unique_marketing_contact_phone_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["project", "-created_at"], name="Marketing_m_project_01e079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["project", "direction"], name="Marketing_m_project_9f8c46_idx"
            ),
        ),
    ]
